library(data.table)
d1 = read.delim("CESC_CPM", header=TRUE, stringsAsFactors=FALSE, row.names=1)
d2 = transpose(d1)
library(Pigengene)
labels=c(rep("FOO", nrow(d2)))
names(labels)=rownames(d2)
p1 = one.step.pigengene(Data=d2, saveDir="delme", bnNum=0, verbose=1, seed=1, toCompact=F, doHeat=T, Labels=labels)
net = hc(p1$pigengene$eigengene)
plot(net)
